version: "3.8"
services:
  myapp:
    container_name: react_c
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - ./myapp:/app
      - ./app/node_modules
